name:               "斯斯"
description:        "Live as a gamer"

url:                "phantom2000x.github.io"
author:             "phantom2000x"
email:              "phantom2000x@icloud.com"
gravatar_hash:      "8cf9cfa09056b2a40e22ef1fa0e1d08f"
twitter:            "phantom2000x"
email:              "phantom2000x@icloud.com"
github:             "phantom2000x"
pinterest:          "ZhesiChen"
linkedin:           "phantom2000x@icloud.com"
facebook:           "zhesisi"

disqus_shortname:   "phantom2000x"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
#  - name:           "Download"
#    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
